# Generated by Django 4.2.3 on 2023-07-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("bookid", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                ("store", models.CharField(max_length=50)),
                ("pub_date", models.DateField()),
            ],
        ),
    ]
